### ISSUE TITLE
Feature request: 3D plot & multiple plots support for "foldedEmbedding"

### ISSUE THREAD

**Issue by whatever60** [derpylz/babyplots_py#1]
I really like this package! It provides handy out-of-box APIs and the plots are pleasing to eyes.

The `folded` and `foldedEmbedding` options are unique ones I've never seen in other visualization packages. The smooth transition from 2D to 3D is awesome.

However, currently it only works if your data is 3D and embedding is 2D, as the name `embedding` implies. And here are my feature requests:

1️⃣  Will similar functionality be added for **two data arrays of the same dimension**?

Maybe like this

```python
bp2.add_plot(
    X,
    'point_cloud',
    'categories',
    Y,
    options=dict(
        alternative=True,  # Enable transition to another set of coordinates
        alternative_data=X_alternative,  # Another set of coordinates of the same dimension as X
    )
)
```

2️⃣️ Besides, it would be nice if we can input **multiple data arrays** and animate the transitions between them.

Maybe like this

```python
bp2.add_plot(
    X,
    'point_cloud',
    'categories',
    Y,
    options=dict(
        alternative=True,  # Enable transition to other sets of coordinates
        alternative_data=[X_alternative1, X_alternative2, ...],  # Other sets of coordinates of the same dimension as X
    )
)
```

Looking forward to reply.

**Comment by derpylz** [comment]
Hi! I'm glad you like the package!

I have some good news for you. I have recently updated the underlying JavaScript package (version 1.2.0), which includes changes to the animation system, making it more flexible. This also includes the possibility to transition from one set of 3D coordinates to another set of 3D coordinates. I think that's what you described in your request 1️⃣.

This update will make its way into the python package shortly.

For your request 2️⃣: There are currently no concrete plans for animating between more than two sets of coordinates, yet. This is mainly because this package at its core is for web based plots, so file size is a limiting factor. Having more sets of coordinates of course increases the file size drastically.

However, there is no real technical issue keeping me from adding this, and since there is interest, I will keep this in mind for the next updates. I'll keep you posted!

**Comment by whatever60** [comment]
Hurray👏

**Comment by derpylz** [comment]
Version 1.2.1 of the python package now has the functionality to animate between two sets of 3D coordinates. The options have been renamed to:

* hasAnimation (formerly folded)
* animationTargets (formerly foldedEmbedding)
* animationDelay (formerly foldAnimDelay)
* animationDuration (formerly foldAnimDuration)
* animationLoop (formerly foldAnimLoop)

You can also find these changes in the updated [documentation](https://bp.bleb.li/documentation/python#pointCloud).

**Comment by whatever60** [comment]
Sorry for the last response, really busy these days, final exams, defenses, these kinds of things.

Finally got time to try it out. Cool new feature🔥, appreciate your work.✨ And an code snippet attached here for future users.

```python
from sklearn import datasets
from babyplots import Babyplot
# load the data set
iris = datasets.load_iris()
X1 = iris.data[:, :3].tolist()  # one set of 3D coordinate
X2 = iris.data[:, 1:].tolist()  # the other set of 3D coordinate
y = iris.target.tolist()  # labels

# create the babyplots visualization
bp = Babyplot()
bp.add_plot(
    X1,
    "pointCloud",
    "categories",
    y,
    {
        "size": 5,
        "shape": "sphere",
        "colorScale": "Set2",
        "showAxes": [True, True, True],
        "axisLabels": ["x", "y", "z"],
        'hasAnimation':True,
        'animationTargets': X2
    }
)
# show the visualization
bp
```

BTW, it seems that the old parameters `folded` and `foldedEmbedding` still work in 1.2.1.
